# Generated by Django 4.1.4 on 2022-12-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_simulation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='racedata',
            name='race_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
